### ISSUE TITLE
Incorrect URL for My BadBlock custom blocklist

### ISSUE THREAD

**Issue by xanderboy2001** [celenityy/bugs#136]
The url specified for My BadBlock returns a 404 error. I believe the correct URL is https://codeberg.org/celenity/BadBlock/raw/branch/pages/abp/badblock.txt

**Comment by celenityy** [comment]
The URL you should use in this case is `https://badblock.celenity.dev/abp/badblock.txt`.

**Comment by celenityy** [comment]
Migrated to our new issue tracker at https://codeberg.org/celenity/bugs/issues/136, hope to see you there!
