### ISSUE TITLE
Suggestion about database

### ISSUE THREAD

**Issue by LexterS999** [celenityy/bugs#23]
Your AdBlock repo is good. Take a look at these two URLs, it can help to increase database:
https://github.com/whotracksme/whotracks.me
https://github.com/whotracksme/whotracks.me/blob/master/whotracksme/data/Readme.md

**Comment by celenityy** [comment]
Will take a look, thank you!

**Comment by celenityy** [comment]
Migrated to our new issue tracker at https://codeberg.org/celenity/bugs/issues/23, hope to see you there!
