### ISSUE TITLE
[BLOCK] *.ui-portal.de, ui-portal.de

### ISSUE THREAD

**Issue by Metrokoto** [celenityy/bugs#34]
### Which domain(s) should be blocked?

*.ui-portal.de, ui-portal.de

### Why should the domain(s) be blocked?

This domain is used by the same company as urbanairship.com and is used for advertising and analytics, yet no other list blocks it.

**Comment by Metrokoto** [comment]
Supporting evidence:
![Screenshot_20241016-145039](https://github.com/user-attachments/assets/d413e32d-f782-48c0-bb4a-3ecd68620390)

**Comment by celenityy** [comment]
Thank you!

Based on your report & my own investigation, I'm going to block:

`ui-dns.biz`
`ui-dns.com`
`ui-dns.de`
`ui-dns.org`
`ui-portal.com`
`ui-portal.de`
`uicdn.com`
`united-internet-media.de`

**Comment by celenityy** [comment]
Migrated to our new issue tracker at https://codeberg.org/celenity/bugs/issues/34, hope to see you there!
